default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: todo_list_app_development
  username: brunobcpro
  password: 202125

test:
  <<: *default
  database: todo_list_app_test
  username: brunobcpro
  password: 202125

production:
  <<: *default
  database: todo_list_app_production
  username: brunobcpro
  password: <%= ENV['TODO_LIST_APP_DATABASE_PASSWORD'] %>
